<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Icon from './components/Icon.vue'
import KnowledgeTree from './components/KnowledgeTree.vue'
import { agents, documents, type KnowledgeDocument } from './data'
import { askKnowledge, demoMode } from './services/rag'
type Message = { id: string; role: 'user' | 'assistant'; content: string; sourceIds: string[]; liked?: boolean; saved?: boolean }
type Conversation = { id: string; title: string; date: string; agentId: string; messages: Message[] }
function read<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(key) || 'null') ?? fallback } catch { return fallback } }
const route = useRoute(), router = useRouter()
const nav = [{ path: '/', name: 'Home', icon: 'Home' }, { path: '/chat', name: 'Dashboard', icon: 'LayoutDashboard' }, { path: '/agents', name: 'AI Agents', icon: 'Bot' }, { path: '/library', name: 'Knowledge Library', icon: 'Folder' }, { path: '/history', name: 'History', icon: 'Clock3' }, { path: '/bookmarks', name: 'Bookmarks', icon: 'Bookmark' }]
const conversations = ref<Conversation[]>(read('mipeers-conversations', []))
const preferences = ref(read('mipeers-preferences', { name: 'Admin', showSources: true, compact: false }))
const currentId = ref(conversations.value[0]?.id || ''), agentId = ref('general'), question = ref(''), search = ref(''), pending = ref(false), error = ref(''), toast = ref(''), mobileNav = ref(false), agentMenu = ref(false), notifications = ref(false)
const drawer = ref(false), selectedDoc = ref<KnowledgeDocument | null>(null), agentDetails = ref(false), messagesEl = ref<HTMLElement | null>(null)
let controller: AbortController | undefined, toastTimer: ReturnType<typeof setTimeout>
const page = computed(() => nav.find(n => n.path === route.path)?.name || 'Settings')
const current = computed(() => conversations.value.find(c => c.id === currentId.value))
const agent = computed(() => agents.find(a => a.id === agentId.value) || agents[0])
const lastAnswer = computed(() => [...(current.value?.messages || [])].reverse().find(m => m.role === 'assistant'))
const results = computed(() => documents.filter(d => `${d.name} ${d.category}`.toLowerCase().includes(search.value.toLowerCase())))
const saved = computed(() => conversations.value.flatMap(c => c.messages.filter(m => m.saved).map(m => ({ ...m, conversation: c }))))
const historyResults = computed(() => conversations.value.filter(c => c.title.toLowerCase().includes(search.value.toLowerCase())))
const suggestions = [{ icon: 'MessageCircle', color: 'purple', label: 'Explore our product', text: 'What are the key features of our product?' }, { icon: 'Code2', color: 'green', label: 'Build an integration', text: 'How do I integrate the API with OAuth?' }, { icon: 'Clock3', color: 'orange', label: 'Understand settlement', text: 'What are the current settlement rules?' }, { icon: 'Shield', color: 'blue', label: 'Find a policy', text: 'What are our data retention policies?' }]
watch(conversations, value => { try { localStorage.setItem('mipeers-conversations', JSON.stringify(value)) } catch { notify('Browser storage is full. Changes will last for this session.') } }, { deep: true })
watch(preferences, value => { try { localStorage.setItem('mipeers-preferences', JSON.stringify(value)) } catch { notify('Unable to save preferences on this device.') } }, { deep: true })
watch(() => route.path, () => { search.value = ''; mobileNav.value = false; notifications.value = false })
watch(() => current.value?.messages.length, async () => { await nextTick(); messagesEl.value?.scrollTo({ top: messagesEl.value.scrollHeight, behavior: 'smooth' }) })
function notify(text: string) { toast.value = text; clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.value = '', 3200) }
function newChat() { if (pending.value) return; currentId.value = ''; question.value = ''; error.value = ''; router.push('/chat') }
function openConversation(c: Conversation) { if (pending.value) return; currentId.value = c.id; agentId.value = c.agentId; router.push('/chat') }
async function send(text = question.value) {
 if (!text.trim() || pending.value) return
 const content = text.trim(); question.value = ''; error.value = ''; pending.value = true
 if (!current.value) { const c: Conversation = { id: crypto.randomUUID(), title: content, date: new Date().toISOString(), agentId: agentId.value, messages: [] }; conversations.value.unshift(c); currentId.value = c.id }
 const c = current.value!; c.messages.push({ id: crypto.randomUUID(), role: 'user', content, sourceIds: [] }); router.push('/chat'); controller = new AbortController()
 try { const response = await askKnowledge({ question: content, agentId: agentId.value, history: c.messages.slice(0, -1).map(m => ({ role: m.role, content: m.content })) }, controller.signal); c.messages.push({ id: crypto.randomUUID(), role: 'assistant', content: response.answer, sourceIds: response.sourceIds }) }
 catch (e) { error.value = e instanceof Error ? e.message : 'Something went wrong. Please try again.'; question.value = content }
 finally { pending.value = false }
}
async function copy(text: string) { try { await navigator.clipboard.writeText(text); notify('Answer copied to clipboard') } catch { notify('Clipboard is unavailable in this browser.') } }
function chooseAgent(id: string) { agentId.value = id; if (current.value) current.value.agentId = id; agentMenu.value = false }
function escape(e: KeyboardEvent) { if (e.key === 'Escape') { drawer.value = false; selectedDoc.value = null; agentDetails.value = false; agentMenu.value = false; notifications.value = false; mobileNav.value = false } }
window.addEventListener('keydown', escape)
const modalOpen = computed(() => drawer.value || !!selectedDoc.value || agentDetails.value)
let previousFocus: HTMLElement | null = null
watch(modalOpen, async (open) => {
 if (open) previousFocus = document.activeElement as HTMLElement
 await nextTick()
 document.querySelectorAll<HTMLElement>('.sidebar, .main-shell').forEach(el => { el.inert = open })
 if (open) document.querySelector<HTMLElement>('.drawer .icon-button')?.focus()
 else previousFocus?.focus()
})
function trapFocus(e: KeyboardEvent) {
 if (!modalOpen.value || e.key !== 'Tab') return
 const items = Array.from(document.querySelectorAll<HTMLElement>('.drawer button:not(:disabled), .drawer input, .drawer a[href]'))
 const first = items[0], last = items[items.length - 1]
 if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus() }
 else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus() }
}
window.addEventListener('keydown', trapFocus)
const toolLife = new AbortController()
const modelContext = (document as Document & { modelContext?: { registerTool: (tool: object, options: { signal: AbortSignal }) => void | Promise<void> } }).modelContext
if (modelContext?.registerTool) {
 try { Promise.resolve(modelContext.registerTool({ name: 'ask_knowledge', description: 'Send a question in the visible knowledge workspace and wait for the answer. Creates a conversation if necessary.', inputSchema: { type: 'object', properties: { question: { type: 'string' } }, required: ['question'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: true }, async execute(input: unknown) { if (!input || typeof input !== 'object' || !('question' in input) || typeof input.question !== 'string' || !input.question.trim()) throw new Error('A non-empty question is required.'); if (pending.value) throw new Error('Wait for the current response.'); await send(input.question); await nextTick(); if (error.value) throw new Error(error.value); return { conversationId: currentId.value, answer: lastAnswer.value?.content }; } }, { signal: toolLife.signal })).catch(() => {}) } catch { /* Browser capability is optional. */ }
}
onBeforeUnmount(() => { toolLife.abort(); window.removeEventListener('keydown', trapFocus) })
onBeforeUnmount(() => { window.removeEventListener('keydown', escape); controller?.abort(); clearTimeout(toastTimer) })
</script>

<template>
 <div :class="['app-shell', { compact: preferences.compact }]">
  <div v-if="mobileNav" class="mobile-backdrop" @click="mobileNav = false"></div>
  <aside :class="['sidebar', { 'mobile-open': mobileNav }]">
   <RouterLink to="/" class="brand" aria-label="MiPeers home"><span class="brand-word">MiP<span class="brand-dot">.</span></span><span class="brand-caption">HUMAN SOFTWARE COMPANY</span></RouterLink>
   <div class="workspace-label">WORKSPACE</div>
   <nav><RouterLink v-for="item in nav" :key="item.path" :to="item.path" :class="['nav-link', { active: route.path === item.path }]"><Icon :name="item.icon"/><span>{{ item.name }}</span><span v-if="item.path === '/bookmarks' && saved.length" class="nav-count">{{ saved.length }}</span></RouterLink></nav>
   <div class="sidebar-bottom"><div class="workspace-status"><span class="status-dot"></span><div>Knowledge workspace<small>{{ demoMode ? 'Demo environment' : 'Connected environment' }}</small></div></div><RouterLink to="/settings" :class="['nav-link', {active: route.path === '/settings'}]"><Icon name="Settings"/><span>Settings</span></RouterLink><button class="profile" @click="router.push('/settings')"><span class="avatar">{{ preferences.name.charAt(0) || 'A' }}</span><span>{{ preferences.name }}<small>Workspace admin</small></span><Icon name="ChevronDown" :size="16"/></button></div>
  </aside>
  <main class="main-shell">
   <header class="topbar"><div class="page-label"><button class="icon-button mobile-toggle" aria-label="Toggle navigation" @click="mobileNav = !mobileNav"><Icon name="Menu"/></button><span class="breadcrumb">Workspace <Icon name="ChevronRight" :size="14"/></span><span>{{ page }}</span></div><div class="header-tools"><div class="global-search"><Icon name="Search" :size="17"/><input v-model="search" aria-label="Search knowledge base" placeholder="Search knowledge base…" @keydown.enter="router.push('/library')"><kbd>↵</kbd><div v-if="search && !['/history','/library'].includes(route.path)" class="search-popover"><button v-for="doc in results" :key="doc.id" @click="selectedDoc = doc; search = ''"><Icon name="FileText" :size="16"/>{{ doc.name }}</button><p v-if="!results.length">No documents found.</p></div></div><span class="demo-pill" v-if="demoMode">Demo</span><div class="notification-wrap"><button class="icon-button notification-button" aria-label="Notifications" @click="notifications = !notifications"><Icon name="Bell"/><i/></button><div v-if="notifications" class="notification-popover"><strong>You're all caught up</strong><p>Your workspace is ready to explore.</p></div></div><button class="avatar small" aria-label="Open profile settings" @click="router.push('/settings')">{{ preferences.name.charAt(0) || 'A' }}</button></div></header>

   <section v-if="route.path === '/'" class="home-page">
    <div class="home-topline"><span class="eyebrow"><span class="status-dot"/> YOUR KNOWLEDGE, CONNECTED</span><span class="subtle">MiPeers workspace</span></div>
    <div class="home-grid"><div class="welcome-area"><div class="welcome"><Icon name="Sparkles"/><span>Welcome back, <strong>{{ preferences.name }}</strong></span></div><h1>How can I help<br>you today<span class="purple-text">?</span></h1><p class="home-description">A little curiosity. A world of knowledge.<br>Find answers in your team's collective expertise.</p><form class="home-composer" @submit.prevent="send()"><div class="home-input-row"><Icon name="Search" :size="23"/><input v-model="question" aria-label="Ask your knowledge base" placeholder="Ask anything or search your knowledge base…"><button class="send-button" :disabled="!question.trim() || pending" aria-label="Send question"><Icon name="ArrowUp" :size="24"/></button></div><div class="composer-foot"><span><Icon name="Sparkles" :size="14"/> {{ agent.short }}</span><span>Enter to ask <span class="enter-key">↵</span></span></div></form><div class="try-heading"><span>Not sure where to start?</span><span class="subtle">Try asking</span></div><div class="suggestions"><button v-for="s in suggestions" :key="s.label" @click="send(s.text)"><span :class="['suggestion-icon', s.color]"><Icon :name="s.icon"/></span><span class="suggestion-label">{{ s.label }}</span><span class="suggestion-question">{{ s.text }}</span><Icon name="ArrowUpRight" class="suggestion-arrow" :size="17"/></button></div></div>
    <aside class="home-rail"><div class="rail-orbit"><Icon name="Sparkles" :size="29"/></div><span class="eyebrow">BUILT AROUND YOUR KNOWLEDGE</span><h2>The right answer.<br>The right source.</h2><p>Bring your questions.<br>We'll help you find a starting point.</p><button class="rail-link" @click="router.push('/agents')"><span class="rail-icon purple"><Icon name="Bot" :size="24"/></span><span>AI Agents<small>A specialist for every question</small></span><Icon name="ChevronRight" :size="17"/></button><button class="rail-link" @click="drawer = true"><span class="rail-icon blue"><Icon name="Folder" :size="24"/></span><span>Knowledge Library<small>Explore your source of truth</small></span><Icon name="ChevronRight" :size="17"/></button><div class="rail-footer"><span class="status-dot"/>{{ documents.length }} sample documents available</div></aside></div><footer class="home-footer"><span><Icon name="Shield" :size="14"/> Your team's knowledge. In one place.</span><span>Powered by <strong>Progress Agentic RAG</strong></span></footer>
   </section>

   <section v-else-if="route.path === '/chat'" class="chat-layout">
    <div class="chat-main"><div class="chat-toolbar"><div class="agent-picker"><button class="agent-select" :disabled="pending" @click="agentMenu = !agentMenu"><span class="agent-orb"><Icon name="Sparkles"/></span><span>{{ agent.name }}</span><span v-if="agent.id === 'general'" class="badge">Default</span><Icon name="ChevronDown" :size="16"/></button><div v-if="agentMenu" class="agent-options"><button v-for="a in agents" :key="a.id" @click="chooseAgent(a.id)"><Icon name="Bot" :size="18"/>{{ a.name }}<Icon v-if="agentId === a.id" name="Check" :size="16"/></button></div></div><button class="icon-button" title="New conversation" aria-label="New conversation" :disabled="pending" @click="newChat"><Icon name="Plus"/></button><button class="icon-button sources-toggle" aria-label="Toggle sources" @click="preferences.showSources = !preferences.showSources"><Icon name="PanelRightClose"/></button></div>
    <div class="messages" ref="messagesEl"><div v-if="!current?.messages.length" class="chat-empty"><span class="large-orb"><Icon name="Sparkles" :size="32"/></span><h2>Let's find your answer.</h2><p>Ask {{ agent.short.toLowerCase() }} a question to get started.</p><button class="outline-button" @click="send('What are the current settlement rules?')">What are the current settlement rules? <Icon name="ArrowUpRight" :size="17"/></button></div><template v-for="message in current?.messages" :key="message.id"><div :class="['message', message.role]"><span v-if="message.role === 'assistant'" class="agent-orb"><Icon name="Sparkles"/></span><div class="message-body"><div v-if="message.role === 'assistant'" class="answer-heading">{{ agent.name }}<span v-if="demoMode" class="subtle">Sample answer</span></div><div class="message-text">{{ message.content }}</div><div v-if="message.role === 'assistant'" class="message-actions"><button aria-label="Copy answer" title="Copy answer" @click="copy(message.content)"><Icon name="Copy" :size="16"/></button><button :aria-pressed="!!message.liked" aria-label="Mark helpful" :class="{ selected: message.liked }" @click="message.liked = !message.liked"><Icon name="ThumbsUp" :size="16"/></button><button :aria-pressed="!!message.saved" :class="{ selected: message.saved }" aria-label="Bookmark answer" @click="message.saved = !message.saved; notify(message.saved ? 'Answer bookmarked' : 'Bookmark removed')"><Icon :name="message.saved ? 'Check' : 'Bookmark'" :size="16"/></button></div><div v-if="message.sourceIds.length" class="answer-sources"><h4><Icon name="BookOpen" :size="16"/> Sources <span>{{ message.sourceIds.length }}</span></h4><button v-for="(id, index) in message.sourceIds" :key="id" @click="selectedDoc = documents.find(d => d.id === id) || null"><span class="source-number">{{ index + 1 }}</span><span>{{ documents.find(d => d.id === id)?.name || id }}</span><small>Pages {{ documents.find(d => d.id === id)?.pages || '—' }}</small><Icon name="ArrowUpRight" :size="14"/></button></div></div></div></template><div v-if="pending" class="thinking" role="status"><Icon name="Sparkles"/> Searching your knowledge<span>•••</span></div><div v-if="error" class="error" role="alert">{{ error }} Your question is below so you can retry.</div></div>
    <div class="chat-bottom"><form class="chat-composer" @submit.prevent="send()"><textarea v-model="question" aria-label="Message" :placeholder="current?.messages.length ? 'Ask a follow-up question…' : 'Ask your knowledge base…'" @keydown.enter.exact.prevent="send()"/><div class="composer-foot"><button type="button" class="text-button" @click="drawer = true"><Icon name="Folder" :size="17"/> Knowledge library</button><div><span><Icon name="Sparkles" :size="14"/> Powered by RAG</span><button class="send-button" :disabled="!question.trim() || pending" aria-label="Send message"><Icon name="ArrowUp" :size="22"/></button></div></div></form><p class="composer-note">{{ demoMode ? 'Demo responses and sample documents. Connect your knowledge service for grounded answers.' : 'AI can make mistakes. Review the original sources for important decisions.' }}</p></div></div>
    <aside v-if="preferences.showSources" class="chat-rail"><section class="panel"><div class="panel-heading"><h3>AI Agent</h3><button @click="agentDetails = true">View details</button></div><div class="agent-summary"><span class="large-orb"><Icon name="Sparkles" :size="25"/></span><div><strong>{{ agent.name }}</strong><p>{{ agent.description }}</p></div></div></section><section class="panel source-panel"><div class="panel-heading"><h3>Knowledge Sources</h3><button @click="drawer = true">View library</button></div><KnowledgeTree :active="lastAnswer?.sourceIds" @open="selectedDoc = $event"/><p class="sources-note"><Icon name="Sparkles" :size="17"/> Highlighted documents are referenced in the latest answer.</p></section></aside>
   </section>

   <section v-else class="content-page"><div class="content-heading"><div><span class="eyebrow">YOUR WORKSPACE</span><h1>{{ page }}</h1><p>{{ route.path === '/agents' ? 'The right expertise for your next question.' : route.path === '/library' ? 'Explore the knowledge behind every answer.' : route.path === '/history' ? 'Pick up where you left off.' : route.path === '/bookmarks' ? 'Useful answers, right where you need them.' : 'Make this workspace yours.' }}</p></div><button v-if="route.path === '/history'" class="primary-button" :disabled="pending" @click="newChat"><Icon name="Plus" :size="18"/>New conversation</button></div>
    <div v-if="route.path === '/agents'" class="agent-cards"><article v-for="a in agents" :key="a.id" class="agent-card"><span :class="['large-orb', a.color]"><Icon name="Bot" :size="28"/></span><span class="badge" v-if="a.id === 'general'">Default agent</span><h2>{{ a.name }}</h2><p>{{ a.description }}</p><div class="tags"><span v-for="tag in a.tags" :key="tag">{{ tag }}</span></div><button class="outline-button" :disabled="pending" @click="chooseAgent(a.id); newChat()">Start conversation<Icon name="ArrowUpRight" :size="18"/></button></article></div>
    <template v-if="route.path === '/library'"><div class="library-toolbar"><span><strong>{{ results.length }}</strong> documents <span class="subtle">· Sample library</span></span><div class="filter-search"><Icon name="Search" :size="17"/><input v-model="search" aria-label="Filter documents" placeholder="Find a document…"/></div></div><div class="document-list"><button v-for="doc in results" :key="doc.id" @click="selectedDoc = doc"><span class="document-icon"><Icon name="FileText"/></span><span><strong>{{ doc.name }}</strong><small>{{ doc.category }} / {{ doc.folder }}</small></span><span class="document-date">{{ doc.date }}</span><Icon name="ArrowUpRight" :size="18"/></button><div v-if="!results.length" class="empty-state"><Icon name="Search" :size="30"/><h2>No matching documents</h2><p>Try a different name or category.</p></div></div></template>
    <template v-if="route.path === '/history'"><div class="filter-search history-search"><Icon name="Search" :size="17"/><input v-model="search" aria-label="Search conversations" placeholder="Search conversations…"/></div><div class="history-list"><article v-for="c in historyResults" :key="c.id"><button class="history-open" :disabled="pending" @click="openConversation(c)"><span class="document-icon"><Icon name="MessageCircle"/></span><span><strong>{{ c.title }}</strong><small>{{ new Date(c.date).toLocaleDateString(undefined, {month: 'short', day: 'numeric'}) }} · {{ c.messages.length }} messages</small></span><Icon name="ChevronRight" :size="18"/></button><button class="icon-button" :disabled="pending" aria-label="Delete conversation" @click="conversations = conversations.filter(item => item.id !== c.id); notify('Conversation deleted')"><Icon name="Trash2" :size="17"/></button></article></div><div v-if="!historyResults.length" class="empty-state"><Icon name="Clock3" :size="34"/><h2>{{ search ? 'No matching conversations' : 'A fresh start' }}</h2><p>Your conversations will appear here after you ask a question.</p><button class="primary-button" @click="newChat">Ask your first question<Icon name="ArrowUpRight" :size="18"/></button></div></template>
    <template v-if="route.path === '/bookmarks'"><div class="bookmark-grid"><article v-for="m in saved" :key="m.id" class="bookmark-card"><div><span class="eyebrow">SAVED ANSWER</span><button class="icon-button" aria-label="Remove bookmark" @click="m.conversation.messages.find(item => item.id === m.id)!.saved = false"><Icon name="Bookmark" :size="18"/></button></div><h2>{{ m.conversation.title }}</h2><p>{{ m.content.slice(0, 230) }}…</p><button class="text-button" :disabled="pending" @click="openConversation(m.conversation)">Open conversation<Icon name="ArrowUpRight" :size="17"/></button></article></div><div v-if="!saved.length" class="empty-state"><Icon name="Bookmark" :size="34"/><h2>Keep the answers that matter</h2><p>Use the bookmark icon under an answer to save it here.</p><button class="outline-button" @click="router.push('/chat')">Go to dashboard<Icon name="ArrowUpRight" :size="17"/></button></div></template>
    <div v-if="route.path === '/settings'" class="settings-panel"><h3>Profile</h3><label class="setting-row"><span>Display name<small>How you appear in this workspace</small></span><input v-model="preferences.name" maxlength="32" placeholder="Admin" aria-label="Display name"/></label><h3>Workspace preferences</h3><label class="setting-row"><span>Knowledge sources<small>Show the source panel beside your conversation</small></span><input type="checkbox" role="switch" v-model="preferences.showSources"/></label><label class="setting-row"><span>Compact navigation<small>Give your content a little more room</small></span><input type="checkbox" role="switch" v-model="preferences.compact"/></label><h3>About this workspace</h3><div class="setting-row"><span>Knowledge service<small>{{ demoMode ? 'Sample answers and documents are enabled' : 'Using your configured knowledge endpoint' }}</small></span><span class="badge">{{ demoMode ? 'Demo mode' : 'Configured' }}</span></div><p class="settings-note">Preferences and conversation history are saved in this browser. This prototype does not include account authentication.</p></div>
   </section>
  </main>
  <div v-if="drawer || selectedDoc || agentDetails" class="overlay" @click.self="drawer = false; selectedDoc = null; agentDetails = false"><section role="dialog" aria-modal="true" :aria-label="selectedDoc ? selectedDoc.name : agentDetails ? 'Agent details' : 'Knowledge library'" :class="['drawer', { 'document-drawer': selectedDoc }]"><div class="drawer-heading"><div><span class="eyebrow">{{ selectedDoc ? 'DOCUMENT PREVIEW' : agentDetails ? 'YOUR AI SPECIALIST' : 'EXPLORE YOUR KNOWLEDGE' }}</span><h2>{{ selectedDoc ? selectedDoc.name : agentDetails ? 'AI Agent' : 'Knowledge Library' }}</h2></div><button class="icon-button" autofocus aria-label="Close panel" @click="selectedDoc ? selectedDoc = null : agentDetails ? agentDetails = false : drawer = false"><Icon name="X"/></button></div><template v-if="selectedDoc"><span class="demo-document-label">Sample document · Preview only</span><p class="subtle">{{ selectedDoc.category }} / {{ selectedDoc.folder }}</p><article class="document-preview"><Icon name="FileText" :size="32"/><h2>{{ selectedDoc.name }}</h2><p>{{ selectedDoc.content }}</p></article><button class="primary-button" :disabled="pending" @click="send('Tell me about ' + selectedDoc.name); selectedDoc = null; drawer = false">Ask about this document<Icon name="ArrowUpRight" :size="17"/></button></template><template v-else-if="agentDetails"><span class="large-orb"><Icon name="Bot" :size="32"/></span><h2>{{ agent.name }}</h2><p>{{ agent.description }}</p><h3>Knowledge scope</h3><div class="tags"><span v-for="tag in agent.tags" :key="tag">{{ tag }}</span></div><p class="subtle">Answers include source references so you can review the supporting documents.</p></template><template v-else><p class="subtle">{{ documents.length }} sample documents across 3 collections</p><KnowledgeTree :active="lastAnswer?.sourceIds" @open="selectedDoc = $event"/></template></section></div>
  <div v-if="toast" class="toast" role="status"><Icon name="Check" :size="18"/>{{ toast }}</div>
 </div>
</template>

