export const agents = [
 { id: 'general', name: 'General Knowledge Agent', short: 'General knowledge', description: 'Your starting point for answers across the entire knowledge base.', tags: ['All knowledge', 'Recommended'], color: 'purple' },
 { id: 'settlement', name: 'Settlement & Clearing Agent', short: 'Settlement & clearing', description: 'Explore settlement policies, procedures, and business calendars.', tags: ['Policies', 'Operations'], color: 'blue' },
 { id: 'product', name: 'Product Specialist', short: 'Product specialist', description: 'Find your way through product features, guides, and API documentation.', tags: ['Product', 'Technical'], color: 'green' }
]
export const documents = [
 { id: 'policy', name: 'Settlement Policy v3.2.pdf', category: 'Settlement & Clearing', folder: 'Settlement Policies', pages: '4–6', date: '03 Sep 2026', content: 'Illustrative document preview\n\nThis demo policy covers settlement timelines, cut-off times, settlement instructions, exception handling, and non-business days.\n\nConnect your knowledge service to retrieve the actual document and verified policy text. The original policy file is not included in this prototype.' },
 { id: 'old-policy', name: 'Settlement Policy v3.1.pdf', category: 'Settlement & Clearing', folder: 'Settlement Policies', pages: '3–5', date: '12 Jun 2026', content: 'Illustrative archived policy. This version is retained for reference. Connect the document service to load version history and original content.' },
 { id: 'procedures', name: 'Settlement Procedures Guide.docx', category: 'Settlement & Clearing', folder: 'Settlement Procedures', pages: '8', date: '01 Sep 2026', content: 'Illustrative procedure guide\n\n1. Review the settlement instruction.\n2. Validate required information.\n3. Monitor processing status.\n4. Escalate exceptions to the operations team.\n\nDemo content only; verify procedures against your connected source.' },
 { id: 'workflow', name: 'Settlement Workflow.pdf', category: 'Settlement & Clearing', folder: 'Settlement Procedures', pages: '1', date: '28 Aug 2026', content: 'Illustrative workflow\n\nInstruction received → Validation → Processing → Reconciliation → Completion.' },
 { id: 'calendar', name: 'Holiday Calendar 2026.pdf', category: 'Settlement & Clearing', folder: 'Calendars & Holidays', pages: '2', date: '15 Jan 2026', content: 'Illustrative calendar preview. Connect your approved business calendar to view holidays and settlement-day adjustments.' },
 { id: 'manual', name: 'Product User Manual.pdf', category: 'Product Documentation', folder: 'Getting Started', pages: '1–3', date: '02 Sep 2026', content: 'Getting started\n\nAsk a question from Home, select a specialist agent, review the sources attached to each response, and bookmark useful answers for later.' },
 { id: 'api', name: 'API Integration Guide.md', category: 'Source Code', folder: 'Developer Guides', pages: '1', date: '04 Sep 2026', content: 'Integration overview\n\nThe frontend calls a configurable application backend through src/services/rag.ts. Keep service credentials on the backend. Return an answer and source identifiers to render citations.' }
]
export type KnowledgeDocument = typeof documents[number]
